package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildRelease")) {
    params {
        expect {
            password("env.KEYSTORE_BASE64", "", label = "Keystore (base64)", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEYSTORE_BASE64", "credentialsJSON:d8ec7d85-67c6-489c-924a-a56c6b12a58d", label = "Keystore (base64)", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.KEYSTORE_PASSWORD", "", label = "Keystore Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEYSTORE_PASSWORD", "credentialsJSON:7e8f0518-49fe-4a7d-a1bf-6ea17299c38a", label = "Keystore Password", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.KEY_PASSWORD", "", label = "Key Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEY_PASSWORD", "credentialsJSON:7e8f0518-49fe-4a7d-a1bf-6ea17299c38a", label = "Key Password", display = ParameterDisplay.HIDDEN)
        }
    }
}
