package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildRelease")) {
    params {
        expect {
            password("env.KEYSTORE_BASE64", "", label = "Keystore (base64)", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEYSTORE_BASE64", "credentialsJSON:8e68a413-5648-4432-9a02-aca550f54e13", label = "Keystore (base64)", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.KEYSTORE_PASSWORD", "", label = "Keystore Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEYSTORE_PASSWORD", "credentialsJSON:72710a07-4c9b-4b6c-84d6-8edcd1df4a27", label = "Keystore Password", display = ParameterDisplay.HIDDEN)
        }
        expect {
            password("env.KEY_PASSWORD", "", label = "Key Password", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.KEY_PASSWORD", "credentialsJSON:72710a07-4c9b-4b6c-84d6-8edcd1df4a27", label = "Key Password", display = ParameterDisplay.HIDDEN)
        }
    }
}
