package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.GOOGLE_SERVICES_JSON", "", label = "google-services.json (base64)", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.GOOGLE_SERVICES_JSON", "credentialsJSON:f29ebb7b-c488-402a-93fc-8c74af6cb1eb", label = "google-services.json (base64)", display = ParameterDisplay.HIDDEN)
        }
    }
}
