package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("github.token", "", label = "GitHub Personal Access Token", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("github.token", "credentialsJSON:543085ac-69ea-4b55-a5b8-31a17c288563", label = "GitHub Personal Access Token", display = ParameterDisplay.HIDDEN)
        }
    }
}
