package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.GOOGLE_SERVICES_JSON", "", label = "google-services.json (base64)", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("env.GOOGLE_SERVICES_JSON", "credentialsJSON:0b91870b-dd45-4ddb-a2d0-59a51c3330fc", label = "google-services.json (base64)", display = ParameterDisplay.HIDDEN)
        }
        add {
            param("env.ANDROID_USER_HOME", """%teamcity.build.checkoutDir%\.android""")
        }
    }
}
