ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.paulcraciunas.chessgym.ApplicationKt.module ]
    }
}

chessgym {
    firebase {
        projectId = "chessgym-local"
        projectId = ${?FIREBASE_PROJECT_ID}
    }
}
